/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_line = 1,
  sym__line_ending = 2,
  sym__blank_line = 3,
  sym__blank_tail = 4,
  sym_document = 5,
  sym_paragraph = 6,
  sym__paragraph_lines_64 = 7,
  sym__paragraph_lines_8 = 8,
  sym__paragraph_line = 9,
  aux_sym_document_repeat1 = 10,
  aux_sym_document_repeat2 = 11,
  aux_sym_paragraph_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line] = "line",
  [sym__line_ending] = "_line_ending",
  [sym__blank_line] = "_blank_line",
  [sym__blank_tail] = "_blank_tail",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [sym__paragraph_lines_64] = "_paragraph_lines_64",
  [sym__paragraph_lines_8] = "_paragraph_lines_8",
  [sym__paragraph_line] = "_paragraph_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line] = sym_line,
  [sym__line_ending] = sym__line_ending,
  [sym__blank_line] = sym__blank_line,
  [sym__blank_tail] = sym__blank_tail,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [sym__paragraph_lines_64] = sym__paragraph_lines_64,
  [sym__paragraph_lines_8] = sym__paragraph_lines_8,
  [sym__paragraph_line] = sym__paragraph_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__paragraph_lines_64] = {
    .visible = false,
    .named = true,
  },
  [sym__paragraph_lines_8] = {
    .visible = false,
    .named = true,
  },
  [sym__paragraph_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 1:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__line_ending);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__line_ending);
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__blank_line);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__blank_line);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym__blank_tail);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line] = ACTIONS(1),
    [sym__line_ending] = ACTIONS(1),
    [sym__blank_line] = ACTIONS(1),
    [sym__blank_tail] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(33),
    [sym_paragraph] = STATE(27),
    [sym__paragraph_line] = STATE(2),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_document_repeat2] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(7),
    [sym__blank_tail] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__paragraph_lines_64] = STATE(4),
    [sym__paragraph_lines_8] = STATE(9),
    [sym__paragraph_line] = STATE(16),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(11),
    [sym__blank_tail] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_paragraph] = STATE(26),
    [sym__paragraph_line] = STATE(2),
    [aux_sym_document_repeat1] = STATE(18),
    [aux_sym_document_repeat2] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(17),
    [sym__blank_tail] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__paragraph_lines_64] = STATE(5),
    [sym__paragraph_lines_8] = STATE(9),
    [sym__paragraph_line] = STATE(16),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(21),
    [sym__blank_tail] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym__paragraph_lines_64] = STATE(5),
    [sym__paragraph_lines_8] = STATE(9),
    [sym__paragraph_line] = STATE(16),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_line] = ACTIONS(27),
    [sym__blank_line] = ACTIONS(25),
    [sym__blank_tail] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(34), 1,
      sym__blank_tail,
    STATE(15), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(32), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [17] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(38), 1,
      sym__blank_tail,
    STATE(14), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [34] = 6,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__blank_tail,
    STATE(2), 1,
      sym__paragraph_line,
    STATE(10), 1,
      aux_sym_document_repeat2,
    STATE(26), 1,
      sym_paragraph,
  [53] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(42), 1,
      sym__blank_tail,
    STATE(7), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(40), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [70] = 6,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      sym_line,
    ACTIONS(49), 1,
      sym__blank_tail,
    STATE(2), 1,
      sym__paragraph_line,
    STATE(10), 1,
      aux_sym_document_repeat2,
    STATE(31), 1,
      sym_paragraph,
  [89] = 6,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym__blank_tail,
    STATE(2), 1,
      sym__paragraph_line,
    STATE(10), 1,
      aux_sym_document_repeat2,
    STATE(28), 1,
      sym_paragraph,
  [108] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(57), 1,
      sym__blank_tail,
    STATE(16), 1,
      sym__paragraph_line,
    STATE(29), 1,
      sym__paragraph_lines_8,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [125] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(61), 1,
      sym__blank_tail,
    STATE(12), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [142] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(65), 1,
      sym__blank_tail,
    STATE(6), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [159] = 5,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(69), 1,
      sym__blank_tail,
    STATE(13), 1,
      sym__paragraph_lines_8,
    STATE(16), 1,
      sym__paragraph_line,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [176] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(73), 1,
      sym__blank_tail,
    STATE(19), 1,
      sym__paragraph_line,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [190] = 4,
    ACTIONS(17), 1,
      sym__blank_line,
    ACTIONS(49), 1,
      sym__blank_tail,
    STATE(18), 1,
      aux_sym_document_repeat1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      sym_line,
  [204] = 4,
    ACTIONS(77), 1,
      sym__blank_line,
    ACTIONS(80), 1,
      sym__blank_tail,
    STATE(18), 1,
      aux_sym_document_repeat1,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_line,
  [218] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(84), 1,
      sym__blank_tail,
    STATE(20), 1,
      sym__paragraph_line,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [232] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(88), 1,
      sym__blank_tail,
    STATE(23), 1,
      sym__paragraph_line,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [246] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(92), 1,
      sym__blank_tail,
    STATE(24), 1,
      sym__paragraph_line,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [260] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(96), 1,
      sym__blank_tail,
    STATE(21), 1,
      sym__paragraph_line,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [274] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(100), 1,
      sym__blank_tail,
    STATE(22), 1,
      sym__paragraph_line,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [288] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(104), 1,
      sym__blank_tail,
    STATE(30), 1,
      sym__paragraph_line,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [302] = 2,
    ACTIONS(108), 1,
      sym__blank_tail,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      sym_line,
      sym__blank_line,
  [311] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym__blank_tail,
    ACTIONS(110), 1,
      sym__blank_line,
    STATE(17), 1,
      aux_sym_document_repeat1,
  [324] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__blank_tail,
    ACTIONS(110), 1,
      sym__blank_line,
    STATE(17), 1,
      aux_sym_document_repeat1,
  [337] = 4,
    ACTIONS(110), 1,
      sym__blank_line,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      sym__blank_tail,
    STATE(17), 1,
      aux_sym_document_repeat1,
  [350] = 2,
    ACTIONS(118), 1,
      sym__blank_tail,
    ACTIONS(116), 3,
      ts_builtin_sym_end,
      sym_line,
      sym__blank_line,
  [359] = 2,
    ACTIONS(122), 1,
      sym__blank_tail,
    ACTIONS(120), 3,
      ts_builtin_sym_end,
      sym_line,
      sym__blank_line,
  [368] = 2,
    ACTIONS(110), 1,
      sym__blank_line,
    STATE(17), 1,
      aux_sym_document_repeat1,
  [375] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      sym__line_ending,
  [382] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [386] = 1,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
  [390] = 1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
  [394] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [398] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 17,
  [SMALL_STATE(8)] = 34,
  [SMALL_STATE(9)] = 53,
  [SMALL_STATE(10)] = 70,
  [SMALL_STATE(11)] = 89,
  [SMALL_STATE(12)] = 108,
  [SMALL_STATE(13)] = 125,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 159,
  [SMALL_STATE(16)] = 176,
  [SMALL_STATE(17)] = 190,
  [SMALL_STATE(18)] = 204,
  [SMALL_STATE(19)] = 218,
  [SMALL_STATE(20)] = 232,
  [SMALL_STATE(21)] = 246,
  [SMALL_STATE(22)] = 260,
  [SMALL_STATE(23)] = 274,
  [SMALL_STATE(24)] = 288,
  [SMALL_STATE(25)] = 302,
  [SMALL_STATE(26)] = 311,
  [SMALL_STATE(27)] = 324,
  [SMALL_STATE(28)] = 337,
  [SMALL_STATE(29)] = 350,
  [SMALL_STATE(30)] = 359,
  [SMALL_STATE(31)] = 368,
  [SMALL_STATE(32)] = 375,
  [SMALL_STATE(33)] = 382,
  [SMALL_STATE(34)] = 386,
  [SMALL_STATE(35)] = 390,
  [SMALL_STATE(36)] = 394,
  [SMALL_STATE(37)] = 398,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 4, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 7, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 7, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 6, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 6, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 5, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 6, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 6, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 5, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 7, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 7, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_line, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_line, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_64, 8, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_64, 8, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_lines_8, 8, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__paragraph_lines_8, 8, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__paragraph_line, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plain_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plain_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
