/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_line = 1,
  sym__line_ending = 2,
  sym__blank_line = 3,
  sym__blank_tail = 4,
  sym_document = 5,
  sym_paragraph = 6,
  aux_sym_document_repeat1 = 7,
  aux_sym_document_repeat2 = 8,
  aux_sym_paragraph_repeat1 = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line] = "line",
  [sym__line_ending] = "_line_ending",
  [sym__blank_line] = "_blank_line",
  [sym__blank_tail] = "_blank_tail",
  [sym_document] = "document",
  [sym_paragraph] = "paragraph",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line] = sym_line,
  [sym__line_ending] = sym__line_ending,
  [sym__blank_line] = sym__blank_line,
  [sym__blank_tail] = sym__blank_tail,
  [sym_document] = sym_document,
  [sym_paragraph] = sym_paragraph,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 1:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__line_ending);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__line_ending);
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__blank_line);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__blank_line);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym__blank_tail);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line] = ACTIONS(1),
    [sym__line_ending] = ACTIONS(1),
    [sym__blank_line] = ACTIONS(1),
    [sym__blank_tail] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(17),
    [sym_paragraph] = STATE(10),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_document_repeat2] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(7),
    [sym__blank_tail] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_paragraph] = STATE(13),
    [aux_sym_document_repeat1] = STATE(7),
    [aux_sym_document_repeat2] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_line] = ACTIONS(5),
    [sym__blank_line] = ACTIONS(13),
    [sym__blank_tail] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_paragraph] = STATE(13),
    [aux_sym_document_repeat2] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_line] = ACTIONS(5),
    [sym__blank_tail] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym_paragraph] = STATE(15),
    [aux_sym_document_repeat2] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_line] = ACTIONS(19),
    [sym__blank_tail] = ACTIONS(22),
  },
  [STATE(5)] = {
    [sym_paragraph] = STATE(12),
    [aux_sym_document_repeat2] = STATE(4),
    [aux_sym_paragraph_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(24),
    [sym_line] = ACTIONS(5),
    [sym__blank_tail] = ACTIONS(26),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_line,
    ACTIONS(30), 1,
      sym__blank_tail,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(28), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [14] = 4,
    ACTIONS(34), 1,
      sym__blank_line,
    ACTIONS(37), 1,
      sym__blank_tail,
    STATE(7), 1,
      aux_sym_document_repeat1,
    ACTIONS(32), 2,
      ts_builtin_sym_end,
      sym_line,
  [28] = 4,
    ACTIONS(41), 1,
      sym_line,
    ACTIONS(44), 1,
      sym__blank_tail,
    STATE(8), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym__blank_line,
  [42] = 4,
    ACTIONS(13), 1,
      sym__blank_line,
    ACTIONS(22), 1,
      sym__blank_tail,
    STATE(7), 1,
      aux_sym_document_repeat1,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      sym_line,
  [56] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym__blank_tail,
    ACTIONS(46), 1,
      sym__blank_line,
    STATE(9), 1,
      aux_sym_document_repeat1,
  [69] = 2,
    ACTIONS(44), 1,
      sym__blank_tail,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_line,
      sym__blank_line,
  [78] = 4,
    ACTIONS(46), 1,
      sym__blank_line,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      sym__blank_tail,
    STATE(9), 1,
      aux_sym_document_repeat1,
  [91] = 4,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      sym__blank_tail,
    ACTIONS(46), 1,
      sym__blank_line,
    STATE(9), 1,
      aux_sym_document_repeat1,
  [104] = 2,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym__line_ending,
  [111] = 2,
    ACTIONS(46), 1,
      sym__blank_line,
    STATE(9), 1,
      aux_sym_document_repeat1,
  [118] = 1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
  [122] = 1,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
  [126] = 1,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
  [130] = 1,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
  [134] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 14,
  [SMALL_STATE(8)] = 28,
  [SMALL_STATE(9)] = 42,
  [SMALL_STATE(10)] = 56,
  [SMALL_STATE(11)] = 69,
  [SMALL_STATE(12)] = 78,
  [SMALL_STATE(13)] = 91,
  [SMALL_STATE(14)] = 104,
  [SMALL_STATE(15)] = 111,
  [SMALL_STATE(16)] = 118,
  [SMALL_STATE(17)] = 122,
  [SMALL_STATE(18)] = 126,
  [SMALL_STATE(19)] = 130,
  [SMALL_STATE(20)] = 134,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(14),
  [22] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plain_text(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plain_text",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
